/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/synthesis-labs/polaris-operator/pkg/apis/polaris/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakePolarisStacks implements PolarisStackInterface
type FakePolarisStacks struct {
	Fake *FakePolarisV1alpha1
	ns   string
}

var polarisstacksResource = schema.GroupVersionResource{Group: "polaris.synthesis.co.za", Version: "v1alpha1", Resource: "polarisstacks"}

var polarisstacksKind = schema.GroupVersionKind{Group: "polaris.synthesis.co.za", Version: "v1alpha1", Kind: "PolarisStack"}

// Get takes name of the polarisStack, and returns the corresponding polarisStack object, and an error if there is any.
func (c *FakePolarisStacks) Get(name string, options v1.GetOptions) (result *v1alpha1.PolarisStack, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(polarisstacksResource, c.ns, name), &v1alpha1.PolarisStack{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PolarisStack), err
}

// List takes label and field selectors, and returns the list of PolarisStacks that match those selectors.
func (c *FakePolarisStacks) List(opts v1.ListOptions) (result *v1alpha1.PolarisStackList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(polarisstacksResource, polarisstacksKind, c.ns, opts), &v1alpha1.PolarisStackList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.PolarisStackList{ListMeta: obj.(*v1alpha1.PolarisStackList).ListMeta}
	for _, item := range obj.(*v1alpha1.PolarisStackList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested polarisStacks.
func (c *FakePolarisStacks) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(polarisstacksResource, c.ns, opts))

}

// Create takes the representation of a polarisStack and creates it.  Returns the server's representation of the polarisStack, and an error, if there is any.
func (c *FakePolarisStacks) Create(polarisStack *v1alpha1.PolarisStack) (result *v1alpha1.PolarisStack, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(polarisstacksResource, c.ns, polarisStack), &v1alpha1.PolarisStack{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PolarisStack), err
}

// Update takes the representation of a polarisStack and updates it. Returns the server's representation of the polarisStack, and an error, if there is any.
func (c *FakePolarisStacks) Update(polarisStack *v1alpha1.PolarisStack) (result *v1alpha1.PolarisStack, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(polarisstacksResource, c.ns, polarisStack), &v1alpha1.PolarisStack{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PolarisStack), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakePolarisStacks) UpdateStatus(polarisStack *v1alpha1.PolarisStack) (*v1alpha1.PolarisStack, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(polarisstacksResource, "status", c.ns, polarisStack), &v1alpha1.PolarisStack{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PolarisStack), err
}

// Delete takes name of the polarisStack and deletes it. Returns an error if one occurs.
func (c *FakePolarisStacks) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(polarisstacksResource, c.ns, name), &v1alpha1.PolarisStack{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakePolarisStacks) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(polarisstacksResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.PolarisStackList{})
	return err
}

// Patch applies the patch and returns the patched polarisStack.
func (c *FakePolarisStacks) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.PolarisStack, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(polarisstacksResource, c.ns, name, data, subresources...), &v1alpha1.PolarisStack{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PolarisStack), err
}
