/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/synthesis-labs/polaris-operator/pkg/apis/polaris/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakePolarisSourceRepositories implements PolarisSourceRepositoryInterface
type FakePolarisSourceRepositories struct {
	Fake *FakePolarisV1alpha1
	ns   string
}

var polarissourcerepositoriesResource = schema.GroupVersionResource{Group: "polaris.synthesis.co.za", Version: "v1alpha1", Resource: "polarissourcerepositories"}

var polarissourcerepositoriesKind = schema.GroupVersionKind{Group: "polaris.synthesis.co.za", Version: "v1alpha1", Kind: "PolarisSourceRepository"}

// Get takes name of the polarisSourceRepository, and returns the corresponding polarisSourceRepository object, and an error if there is any.
func (c *FakePolarisSourceRepositories) Get(name string, options v1.GetOptions) (result *v1alpha1.PolarisSourceRepository, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(polarissourcerepositoriesResource, c.ns, name), &v1alpha1.PolarisSourceRepository{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PolarisSourceRepository), err
}

// List takes label and field selectors, and returns the list of PolarisSourceRepositories that match those selectors.
func (c *FakePolarisSourceRepositories) List(opts v1.ListOptions) (result *v1alpha1.PolarisSourceRepositoryList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(polarissourcerepositoriesResource, polarissourcerepositoriesKind, c.ns, opts), &v1alpha1.PolarisSourceRepositoryList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.PolarisSourceRepositoryList{ListMeta: obj.(*v1alpha1.PolarisSourceRepositoryList).ListMeta}
	for _, item := range obj.(*v1alpha1.PolarisSourceRepositoryList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested polarisSourceRepositories.
func (c *FakePolarisSourceRepositories) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(polarissourcerepositoriesResource, c.ns, opts))

}

// Create takes the representation of a polarisSourceRepository and creates it.  Returns the server's representation of the polarisSourceRepository, and an error, if there is any.
func (c *FakePolarisSourceRepositories) Create(polarisSourceRepository *v1alpha1.PolarisSourceRepository) (result *v1alpha1.PolarisSourceRepository, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(polarissourcerepositoriesResource, c.ns, polarisSourceRepository), &v1alpha1.PolarisSourceRepository{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PolarisSourceRepository), err
}

// Update takes the representation of a polarisSourceRepository and updates it. Returns the server's representation of the polarisSourceRepository, and an error, if there is any.
func (c *FakePolarisSourceRepositories) Update(polarisSourceRepository *v1alpha1.PolarisSourceRepository) (result *v1alpha1.PolarisSourceRepository, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(polarissourcerepositoriesResource, c.ns, polarisSourceRepository), &v1alpha1.PolarisSourceRepository{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PolarisSourceRepository), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakePolarisSourceRepositories) UpdateStatus(polarisSourceRepository *v1alpha1.PolarisSourceRepository) (*v1alpha1.PolarisSourceRepository, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(polarissourcerepositoriesResource, "status", c.ns, polarisSourceRepository), &v1alpha1.PolarisSourceRepository{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PolarisSourceRepository), err
}

// Delete takes name of the polarisSourceRepository and deletes it. Returns an error if one occurs.
func (c *FakePolarisSourceRepositories) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(polarissourcerepositoriesResource, c.ns, name), &v1alpha1.PolarisSourceRepository{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakePolarisSourceRepositories) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(polarissourcerepositoriesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.PolarisSourceRepositoryList{})
	return err
}

// Patch applies the patch and returns the patched polarisSourceRepository.
func (c *FakePolarisSourceRepositories) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.PolarisSourceRepository, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(polarissourcerepositoriesResource, c.ns, name, data, subresources...), &v1alpha1.PolarisSourceRepository{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PolarisSourceRepository), err
}
