/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/synthesis-labs/polaris-operator/pkg/apis/polaris/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakePolarisBuildSteps implements PolarisBuildStepInterface
type FakePolarisBuildSteps struct {
	Fake *FakePolarisV1alpha1
	ns   string
}

var polarisbuildstepsResource = schema.GroupVersionResource{Group: "polaris.synthesis.co.za", Version: "v1alpha1", Resource: "polarisbuildsteps"}

var polarisbuildstepsKind = schema.GroupVersionKind{Group: "polaris.synthesis.co.za", Version: "v1alpha1", Kind: "PolarisBuildStep"}

// Get takes name of the polarisBuildStep, and returns the corresponding polarisBuildStep object, and an error if there is any.
func (c *FakePolarisBuildSteps) Get(name string, options v1.GetOptions) (result *v1alpha1.PolarisBuildStep, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(polarisbuildstepsResource, c.ns, name), &v1alpha1.PolarisBuildStep{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PolarisBuildStep), err
}

// List takes label and field selectors, and returns the list of PolarisBuildSteps that match those selectors.
func (c *FakePolarisBuildSteps) List(opts v1.ListOptions) (result *v1alpha1.PolarisBuildStepList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(polarisbuildstepsResource, polarisbuildstepsKind, c.ns, opts), &v1alpha1.PolarisBuildStepList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.PolarisBuildStepList{ListMeta: obj.(*v1alpha1.PolarisBuildStepList).ListMeta}
	for _, item := range obj.(*v1alpha1.PolarisBuildStepList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested polarisBuildSteps.
func (c *FakePolarisBuildSteps) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(polarisbuildstepsResource, c.ns, opts))

}

// Create takes the representation of a polarisBuildStep and creates it.  Returns the server's representation of the polarisBuildStep, and an error, if there is any.
func (c *FakePolarisBuildSteps) Create(polarisBuildStep *v1alpha1.PolarisBuildStep) (result *v1alpha1.PolarisBuildStep, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(polarisbuildstepsResource, c.ns, polarisBuildStep), &v1alpha1.PolarisBuildStep{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PolarisBuildStep), err
}

// Update takes the representation of a polarisBuildStep and updates it. Returns the server's representation of the polarisBuildStep, and an error, if there is any.
func (c *FakePolarisBuildSteps) Update(polarisBuildStep *v1alpha1.PolarisBuildStep) (result *v1alpha1.PolarisBuildStep, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(polarisbuildstepsResource, c.ns, polarisBuildStep), &v1alpha1.PolarisBuildStep{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PolarisBuildStep), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakePolarisBuildSteps) UpdateStatus(polarisBuildStep *v1alpha1.PolarisBuildStep) (*v1alpha1.PolarisBuildStep, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(polarisbuildstepsResource, "status", c.ns, polarisBuildStep), &v1alpha1.PolarisBuildStep{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PolarisBuildStep), err
}

// Delete takes name of the polarisBuildStep and deletes it. Returns an error if one occurs.
func (c *FakePolarisBuildSteps) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(polarisbuildstepsResource, c.ns, name), &v1alpha1.PolarisBuildStep{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakePolarisBuildSteps) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(polarisbuildstepsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.PolarisBuildStepList{})
	return err
}

// Patch applies the patch and returns the patched polarisBuildStep.
func (c *FakePolarisBuildSteps) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.PolarisBuildStep, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(polarisbuildstepsResource, c.ns, name, data, subresources...), &v1alpha1.PolarisBuildStep{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PolarisBuildStep), err
}
