apiVersion: polaris.synthesis.co.za/v1alpha1
kind: PolarisStack
metadata:
  name: example-polarisstack
spec:
  nickname: teststack
  template: |
    AWSTemplateFormatVersion: 2010-09-09
    Description: 'A test stack'
    Parameters:
        RepositoryName:
            Type: String
            Description: >-
                What should the ECR Repository be named
    Resources:
        ECRRepository:
            Type: AWS::ECR::Repository
            Properties:
                RepositoryName: !Ref RepositoryName
    Outputs:
        RepositoryName:
            Value: !Ref ECRRepository
            Description: Name of the topic
        RepositoryARN:
            Value: !GetAtt ECRRepository.Arn
            Description: ARN of the Repository
  parameters:
    RepositoryName: somethingcool
  finalizers:
  - polaris.cleanup.aws.stack
