apiVersion: polaris.synthesis.co.za/v1alpha1
kind: PolarisBuildPipeline
metadata:
  name: example-pipeline
spec:
  source:
    codecommitrepo: dummyrepo
    branch: dummyref
  builds:
  - name: dummy1
    dockerfilelocation: dummy2
    containerregistry: dummy3
    tag: dummy4