/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// PolarisBuildPipelineListerExpansion allows custom methods to be added to
// PolarisBuildPipelineLister.
type PolarisBuildPipelineListerExpansion interface{}

// PolarisBuildPipelineNamespaceListerExpansion allows custom methods to be added to
// PolarisBuildPipelineNamespaceLister.
type PolarisBuildPipelineNamespaceListerExpansion interface{}

// PolarisBuildStepListerExpansion allows custom methods to be added to
// PolarisBuildStepLister.
type PolarisBuildStepListerExpansion interface{}

// PolarisBuildStepNamespaceListerExpansion allows custom methods to be added to
// PolarisBuildStepNamespaceLister.
type PolarisBuildStepNamespaceListerExpansion interface{}

// PolarisContainerRegistryListerExpansion allows custom methods to be added to
// PolarisContainerRegistryLister.
type PolarisContainerRegistryListerExpansion interface{}

// PolarisContainerRegistryNamespaceListerExpansion allows custom methods to be added to
// PolarisContainerRegistryNamespaceLister.
type PolarisContainerRegistryNamespaceListerExpansion interface{}

// PolarisSourceRepositoryListerExpansion allows custom methods to be added to
// PolarisSourceRepositoryLister.
type PolarisSourceRepositoryListerExpansion interface{}

// PolarisSourceRepositoryNamespaceListerExpansion allows custom methods to be added to
// PolarisSourceRepositoryNamespaceLister.
type PolarisSourceRepositoryNamespaceListerExpansion interface{}

// PolarisStackListerExpansion allows custom methods to be added to
// PolarisStackLister.
type PolarisStackListerExpansion interface{}

// PolarisStackNamespaceListerExpansion allows custom methods to be added to
// PolarisStackNamespaceLister.
type PolarisStackNamespaceListerExpansion interface{}
