/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	polarisv1alpha1 "github.com/synthesis-labs/polaris-operator/pkg/apis/polaris/v1alpha1"
	versioned "github.com/synthesis-labs/polaris-operator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/synthesis-labs/polaris-operator/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/synthesis-labs/polaris-operator/pkg/client/listers/polaris/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// PolarisContainerRegistryInformer provides access to a shared informer and lister for
// PolarisContainerRegistries.
type PolarisContainerRegistryInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.PolarisContainerRegistryLister
}

type polarisContainerRegistryInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewPolarisContainerRegistryInformer constructs a new informer for PolarisContainerRegistry type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewPolarisContainerRegistryInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredPolarisContainerRegistryInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredPolarisContainerRegistryInformer constructs a new informer for PolarisContainerRegistry type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredPolarisContainerRegistryInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.PolarisV1alpha1().PolarisContainerRegistries(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.PolarisV1alpha1().PolarisContainerRegistries(namespace).Watch(options)
			},
		},
		&polarisv1alpha1.PolarisContainerRegistry{},
		resyncPeriod,
		indexers,
	)
}

func (f *polarisContainerRegistryInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredPolarisContainerRegistryInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *polarisContainerRegistryInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&polarisv1alpha1.PolarisContainerRegistry{}, f.defaultInformer)
}

func (f *polarisContainerRegistryInformer) Lister() v1alpha1.PolarisContainerRegistryLister {
	return v1alpha1.NewPolarisContainerRegistryLister(f.Informer().GetIndexer())
}
