/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	polarisv1alpha1 "github.com/synthesis-labs/polaris-operator/pkg/apis/polaris/v1alpha1"
	versioned "github.com/synthesis-labs/polaris-operator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/synthesis-labs/polaris-operator/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/synthesis-labs/polaris-operator/pkg/client/listers/polaris/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// PolarisBuildStepInformer provides access to a shared informer and lister for
// PolarisBuildSteps.
type PolarisBuildStepInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.PolarisBuildStepLister
}

type polarisBuildStepInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewPolarisBuildStepInformer constructs a new informer for PolarisBuildStep type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewPolarisBuildStepInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredPolarisBuildStepInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredPolarisBuildStepInformer constructs a new informer for PolarisBuildStep type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredPolarisBuildStepInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.PolarisV1alpha1().PolarisBuildSteps(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.PolarisV1alpha1().PolarisBuildSteps(namespace).Watch(options)
			},
		},
		&polarisv1alpha1.PolarisBuildStep{},
		resyncPeriod,
		indexers,
	)
}

func (f *polarisBuildStepInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredPolarisBuildStepInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *polarisBuildStepInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&polarisv1alpha1.PolarisBuildStep{}, f.defaultInformer)
}

func (f *polarisBuildStepInformer) Lister() v1alpha1.PolarisBuildStepLister {
	return v1alpha1.NewPolarisBuildStepLister(f.Informer().GetIndexer())
}
